import { DesktopComputerIcon } from "@heroicons/react/solid";
import {
  Block,
  Button,
  Card,
  Flex,
  Icon,
  Text,
  Bold,
  TabList,
  Tab,
  Title,
  Subtitle,
} from "@tremor/react";
import { MinimalHistory } from "../../utils/types";
import DynamicChart from "../DynamicChart";
import SyntaxHighlighter from "react-syntax-highlighter";
import { useState } from "react";

export default function History({
  history: { id, prompt_response, response, created_at },
  onSaveHistory,
  onFetchResults,
}: {
  history: MinimalHistory;
  onSaveHistory: (id: number) => void;
  onFetchResults: (id: number) => void;
}) {
  const [selectedView, setSelectedView] = useState("1");
  const hasResults = response?.results;
  return (
    <Card>
      <Flex
        justifyContent="justify-start"
        alignItems="items-center"
        spaceX="space-x-4"
      >
        <Icon
          variant="light"
          icon={DesktopComputerIcon}
          size="lg"
          color="emerald"
        />
        <Title>Query autogenerated #{id}</Title>
      </Flex>
      <Subtitle>
        <Text truncate={true}>Created on {created_at}</Text>
      </Subtitle>

      <TabList
        defaultValue="1"
        onValueChange={(value) => setSelectedView(value)}
        marginTop="mt-6"
      >
        <Tab value="1" text="SQL" />
        <Tab value="2" text="Result" />
      </TabList>

      {selectedView === "1" && (
        <Block marginTop="mt-20">
          <SyntaxHighlighter
            language="sql"
            customStyle={{
              padding: 40,
              fontSize: 18,
            }}
          >
            {prompt_response || ""}
          </SyntaxHighlighter>
        </Block>
      )}

      {selectedView === "2" && (
        <>
          {hasResults ? (
            <>
              <DynamicChart results={response.results} type={response.type} />
              <Button
                onClick={() => onSaveHistory(id)}
                marginTop="mt-6"
                size="md"
                color="green"
              >
                Save
              </Button>
            </>
          ) : (
            <Button
              onClick={() => onFetchResults(id)}
              marginTop="mt-6"
              size="md"
              color="green"
            >
              {" "}
              Get results
            </Button>
          )}
        </>
      )}
    </Card>
  );
}
